ambassador:
  image: svendowideit/ambassador
  container_name: ambassador
  expose:
   - "6379"
  environment:
    - REDIS_PORT_6379_TCP=tcp://52.27.248.129:6379

redis_client:
  image: relateiq/redis-cli
  container_name: redis_client
  links:
    - ambassador:redis
  ports:
   - 6379:6379
